collections:
  samples:
    output: true

defaults:
  - scope:
      path: "/grove"
      type: "samples"
    values:
      layout: "sample"
  - scope:
      path: "/grove"
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "/grove"
    values:
      layout: "default"

plugins:
  - jekyll-sitemap